[project]
name = "biqbin"
version = "2.0.0"
readme = { file = "README.md", content-type = "text/markdown" }
dependencies = [
  "numpy<2.4",
  "scipy",
  "dwave-samplers",
]

[build-system]
requires = ["scikit-build-core", "pybind11", "numpy==2.3.3"]
build-backend = "scikit_build_core.build"

[tool.scikit-build]
wheel.packages = ["biqbin"]

[project.scripts]
biqbin-maxcut = "biqbin_maxcut:main"
biqbin-qubo = "biqbin_qubo:main"
biqbin-heuristic = "biqbin_heuristic:main"
